== Prefacio

Nuestro bendito Señor dice, "`haced el árbol bueno, y su fruto será también bueno.`"
Por lo tanto,
no es al podar las _ramas_ de la corrupción que los padres de los
jóvenes pueden esperar ser de gran utilidad en su labor;
no más de lo que un médico que simplemente trató
los síntomas en lugar de ir a la raíz de la enfermedad,
podría esperar ver a sus pacientes restaurados a la salud.
Las Escrituras de la verdad lo testifican ampliamente,
que "`hay bálsamo en Galaad`"--que "`hay un médico allí,`"^
footnote:[Jeremías 8:22, 46:11]
para el alma que está enferma de pecado;
y que hay Uno que no está lejos de cada uno de nosotros.
"`Porque este mandamiento que yo te ordeno hoy,`" dice Moisés bajo la autoridad de Dios,
"`no te es encubierto, ni está lejos, porque _muy cerca de ti_ está la palabra,
en tu boca y en tu corazón, para que la cumplas.`"^
footnote:[Deuteronomio 30:11-14 RV1602 Purificada]

Por lo tanto, no hay nada más importante,
y nunca es demasiado pronto para dirigir la atención de los niños a un verdadero conocimiento
y experiencia de _esta Palabra en el corazón._
Esta obra se publicó con este fin,
con la humilde esperanza de poder brindar alguna ayuda a través
de este modo de instrucción que la autora ha encontrado útil,
y que es presentado aquí como
pistas para que los padres las sigan y las amplíen,
según se presente la oportunidad;
porque la enseñanza más efectiva es la que surge de las circunstancias,
y la que se acerca al corazón mientras los sentimientos están frescos y vivos.

Si se alega que el enfoque planteado aquí se limita a la educación de mujeres jóvenes,
mi respuesta sería que la _idea general_ (que es todo lo que la autora pretende exponer),
es igualmente aplicable para ambos sexos.
