== Diálogo I

[quote.section-epigraph, , Salmos 43:3]
____
_Envía tu luz y tu verdad; éstas me guiarán._
____

[.discourse-part]
_Mamá:_ María, si deseas quitar las malas hierbas del jardín, ¿irías a hacerlo de noche?

[.discourse-part]
_María:_ No, mamá; porque no podría ver las malas hierbas.

[.discourse-part]
_Mamá:_ ¿Puedes ver las malas hierbas en tu corazón?

[.discourse-part]
_María:_ Yo no creo que las malas hierbas crezcan allí. . Mamá:
¿No te pinchan a veces los pensamientos molestos e impacientes como ortigas,
cuando te pido que hagas algo que no te gusta hacer?; por ejemplo,
¿cuándo has hecho mal las matemáticas y tienes que volverlas a hacer?

[.discourse-part]
_María:_ No me siento muy cómoda en esos momentos.

[.discourse-part]
_Mamá:_ ¿Y nunca sientes como si te pincharan con espinas u ortigas,
cuando ves que admiran a una de tus jóvenes compañeras más que a ti?

[.discourse-part]
_María:_ Siento algo muy parecido.

[.discourse-part]
_Mamá:_ ¿Son estos sentimientos como flores bonitas, o son como horribles malas hierbas?

[.discourse-part]
_María:_ Son como hierbas muy feas, mamá. . Mamá:
¿Puedes ver lo feas que son mientras te pinchan y te ortigan?

[.discourse-part]
_María:_ No, mamá; porque si lo viera, las arrancaría en seguida, porque son muy feas.
Me pregunto por qué no veo lo feas que son cuando me están ocasionando tanto dolor.

[.discourse-part]
_Mamá:_ ¿No me dijiste que no podías ver las malas hierbas del jardín cuando es de noche?

[.discourse-part]
_María:_ Pero, mamá, ¿es de noche en mi corazón?

[.discourse-part]
_Mamá:_ Cuando te dejas llevar por los malos sentimientos y actitudes, y por la envidia,
haces con tu mente lo mismo que yo haría con esta habitación, si cerrara las persianas.
Si lo hiciera, ¿no impediría que el sol entrara en la habitación, y me diera luz?

[.discourse-part]
_María:_ Pero, mamá, me desconciertas;
hablas de la luz y las tinieblas como si tuviera a ambas en mi interior,
y como si a veces fuera de día y a veces de noche en mi
corazón. Puedo ver con mis ojos el día y la noche;
pero ¿cómo puedo ver lo que pasa en mi corazón?

[.discourse-part]
_Mamá:_
No puedes ver lo que pasa en tu corazón de la misma
manera como ves la diferencia entre el día y la noche;
pero aún así puedes distinguir tan fácilmente el bien del mal en tu corazón,
como la luz de las tinieblas en esta habitación. ¿Tú ves cuando estás haciendo mal,
verdad, cuando estás impaciente, molesta, y con envidia?

[.discourse-part]
_María:_ Sí, mamá. . Mamá: Y,
¿puedes ver que haces bien cuando te esfuerzas por
contener esos malos sentimientos y actitudes,
y no permites que aparezcan?

[.discourse-part]
_María:_ Sí mamá, ahora puedo verlo claramente: entonces supongo,
que ahora es de día en mi corazón, ¿no es así?

[.discourse-part]
_Mamá:_ Sí, ahora estás permitiendo que la luz verdadera brille; estás quieta y humilde,
y dispuesta a ser instruida;
y las persianas de los malos sentimientos y actitudes
no están puestas para oscurecer tu corazón. . María:
Mamá, ¿a qué te refieres con permitir que la luz verdadera brille?
¿Qué es esta luz verdadera?

[.discourse-part]
_Mamá:_ Ve al primer capítulo del evangelio de Juan, en el versículo nueve, y léemelo.

[.discourse-part]
_María:_ "`Aquél era la Luz verdadera, que alumbra a todo hombre que viene a este mundo.`"

[.discourse-part]
_Mamá:_ Esto fue dicho de Jesucristo, mi niña; y ahora ve al capítulo doce,
y lee el versículo cuarenta y seis, lo que Él mismo dice al respecto.

[.discourse-part]
_María:_ "`Yo, la luz, he venido al mundo,
para que todo aquel que cree en mí no permanezca en tinieblas.`"^
footnote:[Reina Valera de Gómez]

[.discourse-part]
_Mamá:_ Ahora ve al capítulo tres,
y lee el versículo diecinueve y los dos versículos siguientes.

[.discourse-part]
_María:_ "`Y ésta es la condenación; que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"

[.discourse-part]
_Mamá:_ A partir de estos textos de la Escritura, aprendes varias cosas importantes;
primero,
aprendes que hay una luz verdadera que alumbra el corazón de cada persona en el mundo,
y que esta luz verdadera es el Señor Jesucristo, el Salvador de los pecadores.
Luego, se te ha dicho, que los que creen en esta luz no permanecen en tinieblas.

[.discourse-part]
_María:_ ¿Estos nunca tienen tinieblas en sus corazones, mamá?

[.discourse-part]
_Mamá:_ Cuando las tinieblas llegan, ellos no permanecen en ella; esto es,
cuando los malos sentimientos y actitudes llegan,
como una nube oscura sobre sus corazones, ellos se alejan de ellos.
Se refugian tan rápido como pueden.
No permanecen en las tinieblas,
de la misma forma que tú no permanecerías en el jardín durante una tormenta.

[.discourse-part]
_María:_ ¿Dónde se refugian, mamá?

[.discourse-part]
_Mamá:_ Se refugian en la luz en la que creen; es decir,
se mantienen cerca de sus instrucciones;
y cuando surgen los temperamentos oscuros y tormentosos,
la luz siempre los guía a permanecer callados y quietos, sin decir o hacer nada,
hasta que se sientan en reposo y con calma.
¿Nunca te has metido en problemas por tener las emociones fuera de control?

[.discourse-part]
_María:_ Sí, mamá. Recuerdo que, una vez, cuando me pidieron hacer un trabajo,
cuando yo quería estar jugando, estaba tan molesta que tensé el hilo hasta romperlo,
y tú me mandaste a que saliera de la habitación.

[.discourse-part]
_Mamá:_
Ahora puedes ver que hiciste mal dándole cabida a este sentimiento oscuro y violento;
y que, si hubieras sido paciente y obediente a tus padres,
te habrías librado del dolor y la desgracia, y no sólo habrías sido más feliz,
sino una niña más buena.

[.discourse-part]
_María:_ Oh, sí mamá; ahora lo veo claramente.

[.discourse-part]
_Mamá:_ Tienes algo en ti, entonces, que te muestra lo que es bueno.
Hace que el bien se manifieste.
Ahora, la Escritura dice: "`la luz es lo que manifiesta todo.`"^
footnote:[Efesios 5:13]
Por lo tanto, este _algo,_ que te muestra lo que es bueno, es la luz.
Es la luz del buen Espíritu de Dios que brilla en tu corazón,
y te muestra que debes obedecer a tus padres.
También te enseña, que está mal perder el control de tus emociones; por lo tanto,
no debes ponerte en este estado; porque si lo haces, te alejas de la luz,
y vas a una oscuridad muy grande.
Pero las personas que no controlan sus malos sentimientos y actitudes,
no se vuelven a esta luz, como me leíste en uno de los pasajes:
"`Porque todo aquel que hace lo malo,
aborrece la luz;`" es decir aborrece ver que está equivocado.
"`Mas el que practica la verdad,`" es decir,
el que teme verdaderamente ofender al Señor y trata de complacerlo en todas las cosas,
este "`viene a la luz;`" viene a la quietud, paciencia, mansedumbre y oración;
todo lo cual, la luz le enseña a amar; y así que él a menudo le dice al Señor,
"`¡Envía tu luz y tu verdad; éstas me guiarán!`"^
footnote:[Salmo 43:3]
