== Diálogo II

[quote.section-epigraph, , Salmos 119:37]
____
_Aparta mis ojos, que no vean la vanidad._
____

[.discourse-part]
_Mamá:_ María, anoche,
cuando dijiste que deseabas ser lo suficientemente
mayor para quedarte después de la cena,
no te respondí, porque ya era muy tarde para entrar en una conversación;
pero ahora me gustaría escuchar si esa es la única razón por la que deseas ser mayor.

[.discourse-part]
_María:_ ¡Oh no, mamá! Hay muchas otras razones por las que desearía ser mayor.
Me gustaría ser tan grande como tú, para poder hacer lo que tú haces.

[.discourse-part]
_Mamá:_ Supongo te gustaría vestir como yo.

[.discourse-part]
_María:_ Sí, creo que me gustaría.

[.discourse-part]
_Mamá:_ ¿Y organizar la cena,
y dirigir a los criados en lo que tienen que hacer?

[.discourse-part]
_María:_ Oh, sí mamá; me gustaría mucho eso.
A menudo juego que estoy organizando la cena.

[.discourse-part]
_Mamá:_ Entonces supongo, que tratas de fingir que eres yo,
y que haces las cosas como yo las hago.

[.discourse-part]
_María:_ Sí, mamá; es muy agradable pensar que soy tú.

[.discourse-part]
_Mamá:_ Entonces, mi querida, lamento mucho interrumpir tu juego,
porque a tu edad es necesario que te diviertas;
sin embargo,
debo decirte que este deseo de ser más grande de lo que eres,
y de fingir ser alguien más que la pequeña niña que eres, es fomentar una emoción mala.

[.discourse-part]
_María:_ Oh, mamá, ¿cómo puede ser malo desear ser tan grande como tú? Porque,
si fuera tan grande como tú, sabría tanto como tú,
y entonces no tendrías que tomarte la molestia de enseñarme.

[.discourse-part]
_Mamá:_ Pero,
no recuerdo que desearas ser mayor para que pudieras ser más _sabia_ de lo que eres ahora.
Creo que era para poder vestirte como yo, y para dirigir a los criados; y, en resumen,
para ser más importante de lo que eres ahora.
No te gusta que te miren como a una niña.

[.discourse-part]
_María:_ No creo que quiera ser importante, mamá;
no creo que me importe que me consideren una niña.

[.discourse-part]
_Mamá:_ Tal vez no te des cuenta,
mi querida; pero ese es el principal deseo de tu corazón al querer ser alguien mayor;
y esa es el sentimiento que está mal fomentar.
Las niñas y los niños pequeños son muy propensos a ser extremadamente vanos y ambiciosos.

[.discourse-part]
_María:_ ¿Qué significa ser ambicioso?

[.discourse-part]
_Mamá:_ Ser ambicioso,
es estar ansioso por llamar la atención. ¿Nunca has visto
a algún niño o niña que le guste llamar la atención?

[.discourse-part]
_María:_ Oh,
sí mamá. Mariana está punto de llorar cuando entra
en la habitación y nadie se fija en ella.
¿No es eso una tontería? ¡Estoy segura de que a mí no me importaría!

[.discourse-part]
_Mamá:_ Bueno, ella es una niñita muy linda,
y me atrevo a decir que ha estado muy acostumbrada a llamar la atención. Pero,
ahora pareces bastante seria, querida.
¿Estás cansada de hablar conmigo?

[.discourse-part]
_María:_ Oh no mamá, no estoy cansada.
Pero, ¡estoy muy sorprendida de escucharte decir que Mariana es linda!

[.discourse-part]
_Mamá:_ ¿No crees, mi querida María, que si en lugar de decir: "`mamá,
estoy muy sorprendida de que pienses que Mariana es linda,`" dijeras,
"`estoy tan molesta o enojada,`" estarías diciendo la verdad?
Ven, piensa un poquito.
¿No es verdad?

[.discourse-part]
_María:_ Pero te reirías de mí si te dijera eso.

[.discourse-part]
_Mamá:_ ¿Por qué piensas que me reiría?

[.discourse-part]
_María:_ Porque sería muy tonto enojarme por eso.

[.discourse-part]
_Mamá:_
Te sentirías muy avergonzada si alguien se diera cuenta
de que estás enfadada porque Mariana fue elogiada,
¿no es así?

[.discourse-part]
_María:_ Oh sí, mamá, de seguro lo estaría.

[.discourse-part]
_Mamá:_ Entonces, mi querida,
¿puedes ver qué vergonzoso es estar ansiosa por llamar la atención?

[.discourse-part]
_María:_ Pero, mamá, ¿estoy ansiosa por llamar la atención?

[.discourse-part]
_Mamá:_ Sí, querida niña, tanto como Mariana;
de otra manera no te hubieras molestado al escuchar sus elogios.
Ahora puedes vislumbrar la oscuridad que hay en tu corazón,
y también la luz verdadera que exhibe la oscuridad,
y conduce al camino correcto para salir de ella.

[.discourse-part]
_María:_ No te entiendo mamá.

[.discourse-part]
_Mamá:_ Bueno, trataré de explicártelo;
pero primero debo hacerte una pregunta, que espero que contestes con la verdad,
porque todo lo que tengo que decirte depende de ella.

[.discourse-part]
_María:_ ¡Oh, mamá! Estoy segura de que responderé con la verdad.
Pregúntame, por favor.

[.discourse-part]
_Mamá:_ ¿No te molestaste, muchísimo, cuando te dije que Mariana era una niña muy linda?

[.discourse-part]
_María:_ Bueno mamá, sí, creo que me molesté bastante; ¡pero no te rías de mí!

[.discourse-part]
_Mamá:_ No debes temer eso, mi niña. Si no conociera de un remedio para tu molestia,
lloraría amargamente, en lugar de reírme por ello.
Pero, para tu dicha, hay algo muy cerca de ti,
que puede quitarte ese sentimiento malo y tonto que te hace molestar.

[.discourse-part]
_María:_ ¿Qué es lo que me hace molestar, mamá?

[.discourse-part]
_Mamá:_ La _envidia_ es el nombre de ese mal sentimiento;
es una mala hierba oscura y muy fea,
que es capaz de crecer muy rápido si no se arranca tan pronto como la notemos.

[.discourse-part]
_María:_ Pero, ¿es posible ver siempre dónde crece?

[.discourse-part]
_Mamá:_ Podríamos, si prestáramos atención a eso que nos lo muestra.

[.discourse-part]
_María:_ ¿Qué es eso, mamá?

[.discourse-part]
_Mamá:_ La luz verdadera, de la que te hablé ayer.
Esta luz es lo bueno que te muestra que es muy vergonzoso
molestarse porque escuchas que otra persona es elogiada,
y que tienes motivos para temer que todos los que supieran de tu envidia,
te despreciarían por ello.
Es esta luz verdadera la que te hace consciente de
que mereces que se rían de ti por esto;
es decir,
te hace sentir lo egoísta y vergonzoso que es envidiar
que otros piensen bien de alguien más.

[.discourse-part]
_María:_ Pero, mamá,
¿cómo es que muestra la manera de deshacerse de este sentimiento tan horrible?

[.discourse-part]
_Mamá:_
¿No es suficiente que te diga que hay un sentimiento malo en tu corazón? Supongamos que,
mientras camino esta tarde delante de la casa de mi vecina, la señora López,
veo a un ladrón entrando por una de las ventanas,
y voy y le digo a ella que había un ladrón en su casa; ¿crees que ella diría:
"`No te preocupes; no me importa si me roba o no`"?

[.discourse-part]
_María:_ No mamá, creo que ella estaría muy agradecida contigo,
y haría todo lo posible por atrapar al ladrón.

[.discourse-part]
_Mamá:_ Entonces,
¿qué hace este sentimiento bueno que te hace avergonzarte de ser envidiosa--tan
avergonzada que no puedes hablar de él por miedo de que se rían de ti?
--¿Qué es lo que hace por ti, sino decirte que hay un ladrón en tu corazón,
un sentimiento malo y perverso,
que te robará todo lo amable y bueno si no lo echas fuera?
Verdaderamente, te robará todo el amor por tus amiguitos; porque,
¿cómo puedes amar a Mariana, si te molesta escuchar que la gente la elogia?

[.discourse-part]
_María:_ ¡Oh, pero, mamá, ser elogiada por ser bonita!
Te he escuchado a menudo decir, que es lamentable ser elogiada por ser linda,
o inteligente, o cualquier otra cosa por el estilo.

[.discourse-part]
_Mamá:_ Sí, María, eso creo.
De hecho, me parece algo muy lamentable,
que me pregunto ¿cómo puedes molestarte al oír que una niñita sea elogiada por su belleza?

[.discourse-part]
_María:_ ¡Oh, mamá! ¡Cómo expones lo que hay dentro de mí!

[.discourse-part]
_Mamá:_ Eso es justamente lo que quiero hacer,
querida mía. Quiero que veas el interior de tu corazón.

[.discourse-part]
_María:_ Me parece muy feo,
creo.

[.discourse-part]
_Mamá:_ Verdaderamente lo es.
Se nos dice en las Escrituras, que "`engañoso es el corazón más que todas las cosas,
y perverso.`"^
footnote:[Jeremías 17:9]
Puedes ver ahora cuán engañoso es el tuyo,
en que te llevó a pensar que no querías ser importante,
y que no estabas ansiosa por llamar la atención, y, en resumen,
que estabas totalmente libre de la vanidad; mientras que,
ahora descubres que la vanidad es la raíz de todos estos
sentimientos malos de los que hemos estado hablando.
Pues si no tuvieras vanidad, no querrías llamar la atención;
y si no quisieras llamar la atención, no te molestaría que Mariana,
o cualquier otra persona fuera elogiada.
Y si no tuvieras vanidad, no fingirías, en tu juego, ser una persona de importancia,
ni te gustaría imaginar que estás ordenando la cena y dirigiendo a los criados, etc.

[.discourse-part]
_María:_ Pero, mamá, ¿qué hay de malo en eso?

[.discourse-part]
_Mamá:_ Hablaremos más sobre este tema mañana.
Ya hemos hablado bastante de ello por hoy;
solamente añadiré unas cuantas palabras respecto a la luz verdadera,
que muestra el sentimiento oscuro y malvado.

[.discourse-part]
_María:_ Me gustaría, mamá;
pues no entiendo completamente cómo ella aleja de mí ese sentimiento malo.

[.discourse-part]
_Mamá:_ Bueno, supón que cuando le diga a la Sra.
López que el ladrón está en su casa, ella me dijera:
"`¿Qué puedo hacer para librarme de él?`" y yo le respondiera:
"`No eres capaz de sacarlo tú sola; pero conozco a un amigo muy amable,
que es lo suficientemente fuerte para sacar a toda
una pandilla de ladrones;`" ¿qué crees que ella haría?

[.discourse-part]
_María:_ Te rogaría que trajeras a ese amigo para que la ayudara,
o iría y le pediría ella misma que la ayudara.

[.discourse-part]
_Mamá:_ ¿Y cómo se lo pediría? ¿Lo haría de una manera fría, despreocupada e indiferente,
o lo haría con mucha determinación?

[.discourse-part]
_María:_ ¡Oh,
con mucha determinación! Tiene que realmente desear
ser ayudada para poder librarse del ladrón,
lo sabes.

[.discourse-part]
_Mamá:_ Pues bien, mi querida hija, cuando este ladrón--la Vanidad--está en tu corazón,
robándote los sentimientos amables y agradables, y llenándote con unos muy malos,
y trayendo así una oscura nube tormentosa sobre ti,
presta atención a lo que la verdadera luz te muestra,
y encontrarás que ella te enseña lo siguiente: _En primer lugar,_
que el malvado ladrón se ha metido en tu corazón; _luego,_
que debes estar quieta y en silencio,
y esperar ver cuál es la mejor forma de librarte de él; _tercero,_
que no puedes hacer nada por ti misma para expulsarlo; y _finalmente,_
que el Espíritu bueno, amoroso y tierno de tu Padre, que está en los cielos,
es el único vencedor de este ladrón; y Él lo vence de esta manera,
expulsándolo de tu corazón, y entrando Él mismo allí.

[.discourse-part]
_María:_ ¡Oh, mamá! Cuán dulce debe ser eso, tener al buen Espíritu en mi corazón,
en lugar del malo, oscuro y malvado.
Pero, ¿crees que Él vendrá por Sí mismo?

[.discourse-part]
_Mamá:_ No, debes pedirlo; de la misma forma como la Sra.
López debe pedirlo,
si quiere la ayuda del buen amigo para sacar al ladrón.
Y este pedir por el Espíritu es llamado oración;
y se te asegura en las Escrituras que no lo pedirás en vano.
Ve al capítulo 11 de Lucas, en el versículo 13, y léemelo.

[.discourse-part]
_María:_ "`Pues si vosotros, siendo malos, sabéis dar buenas dádivas a vuestros hijos,
¿cuánto más vuestro Padre celestial dará el Espíritu Santo a los que se lo pidan?`"

[.discourse-part]
_Mamá:_ Entonces, querida niña, solo debes pedir la ayuda de este bendito Espíritu,
para que saque toda maldad de tu corazón. Y este
buen Espíritu te enseñará a orar por lo que necesites;
porque te hará sentir y ver qué es lo que más necesitas; y a menudo te hará decir,
"`Aparta mis ojos, oh Señor, que no vean la vanidad.`"
