== Diálogo III

[quote.section-epigraph, , Salmos 51:10]
____
_Crea en mí, oh Dios, un corazón limpio,
y renueva un espíritu recto dentro de mí._
____

[.discourse-part]
_María:_ Mamá, me puedes decir hoy,
¿por qué no está bien que yo juegue a que estoy dirigiendo la cena, y fingiendo ser tú?

[.discourse-part]
_Mamá:_ Sí, querida hija; pero en primer lugar,
te haré unas cuantas preguntas sobre el tema.
¿Por qué, de vez en cuando, mientras juegas este tipo de juegos fingidos,
te vuelves para ver si yo te estoy observando?; ¿y si que crees que lo hago,
te ves avergonzada y sonrojada?
¿Por qué pasa esto?
No te muestras avergonzada,
ni te pones a reír cuando te veo mientras juegas con tus rompecabezas,
o cuando armas tus mapas.

[.discourse-part]
_María:_ Porque no me importa que me mires cuando hago estas cosas, mamá.

[.discourse-part]
_Mamá:_ Pero,
¿sí te importa que te vea en el otro juego?

[.discourse-part]
_María:_ Sí, no me gusta.

[.discourse-part]
_Mamá:_ ¿Por qué no te gusta?

[.discourse-part]
_María:_ Porque me da miedo que te rías de mí.

[.discourse-part]
_Mamá:_ ¿Por qué me reiría de ti, querida?

[.discourse-part]
_María:_ Pensarías que es muy tonto.

[.discourse-part]
_Mamá:_ Pero, ¿pienso que es tonto que juegues con la bola,
o que corras con tu aro alrededor del jardín, o que saltes a la cuerda,
o que te entretengas en muchos otros juegos que podría mencionar?

[.discourse-part]
_María:_ Oh, no mamá, esas cosas no son tontas.

[.discourse-part]
_Mamá:_ Pero, ¿crees que es tonto fingir ser yo, o ser alguien más que no seas tú?

[.discourse-part]
_María:_ No sé si alguna vez he pensado en eso.

[.discourse-part]
_Mamá:_ Pero,
¿estás segura de que no te gusta que yo te vea cuando estás fingiendo ser yo?

[.discourse-part]
_María:_ ¡Oh, sí mamá! Estoy muy segura de que eso no me gusta.

[.discourse-part]
_Mamá:_ Entonces, querida mía,
creo que deberías tomarlo como una señal de que hay algo malo en esa forma de jugar,
si no te gusta que te descubran cuando lo haces.

[.discourse-part]
_María:_ ¿Qué es mamá, lo que hace que me disguste cuando me descubres?

[.discourse-part]
_Mamá:_ Es el sentimiento bueno que quiero que observes,
y que le prestes atención. En pocas palabras,
es la luz verdadera que te muestra algo de lo tonto que es jugar de esa forma;
y la necedad, incluso en un niño, es algo que hay que mantener sometido,
tanto como se pueda.
No quieres ser una niña necia, ¿cierto?

[.discourse-part]
_María:_ Oh no, mamá; por eso quiero ser una mujer,
porque la gente piensa que los niños son necios.

[.discourse-part]
_Mamá:_ Yo no creo que los niños sean necios porque son niños,
sino porque tienen una naturaleza necia.

[.discourse-part]
_María:_ Mamá, cuando eras una niña pequeña, ¿tenías una naturaleza necia?

[.discourse-part]
_Mamá:_ Sí, mi querida, y aún tengo la misma naturaleza; solo que el buen Espíritu,
la luz verdadera,
me muestra cuando esa naturaleza se levanta y entonces
me alejo de ella tan pronto como pueda.

[.discourse-part]
_María:_ Pero, mamá, nunca juegas a fingir y a hacerte pasar por alguien más.

[.discourse-part]
_Mamá:_ La naturaleza necia no opera de esa forma conmigo ahora,
porque estoy muy grande como para jugar como tú lo haces;
pero llenaría mi cabeza con muchas ideas vanas y ociosas sobre mí misma,
si yo se lo permitiera.

[.discourse-part]
_María:_ Mamá, ¿todo el mundo tiene esa naturaleza necia?

[.discourse-part]
_Mamá:_ Sí, y eso es lo que los hace actuar de forma tan necia.
Las niñitas que no tienen padres o tutores que les adviertan del peligro de ello,
como lo estoy haciendo ahora contigo,
no tienen ninguna idea de su verdadera condición. Ellas fingen ser alguien importante,
hasta que realmente creen que lo son;
y entonces crecen siendo niñas vanidosas y engreídas,
preguntándose por qué nadie las admira tanto como ellas se admiran a sí mismas.

[.discourse-part]
_María:_ Mamá, creo que nunca más volveré a jugar a fingir.
Realmente es una necedad.

[.discourse-part]
_Mamá:_ El juego no es lo primero que debes dejar, querida,
sino eso que ocasiona que juegues de esta manera.

[.discourse-part]
_María:_ ¿Qué es eso, mamá?

[.discourse-part]
_Mamá:_ La mente vana, mi querida, la naturaleza necia, la parte mala, las malas,
oscuras y horribles hierbas de las que tanto hemos estado hablando;
éstas son las que deben ser sacadas de tu corazón. Ahora,
la luz verdadera siempre te muestra cuándo y dónde brotan,
y te hace sentir vergüenza de ellas.
Presta bastante atención a los sentimientos de vergüenza, porque por lo general,
ellos provienen del buen Espíritu.
¿Sabes a qué me refiero,
cuando te digo que le prestes atención a los sentimientos de vergüenza, cierto?

[.discourse-part]
_María:_ Creo que sí, mamá. Me pides que renuncie a cualquier cosa que vaya a hacer,
si siento que me podría sentir avergonzada de que alguien me vea cuando lo hago.

[.discourse-part]
_Mamá:_ Sí, eso quería decir.
Por ejemplo, si yo entrara en la habitación y te encontrara abriendo mis gavetas,
o mirando entre mis papeles, o tomando algún pastel o golosinas de la mesa,
¿no te sentirías avergonzada?

[.discourse-part]
_María:_ Oh sí, mamá, muy avergonzada.

[.discourse-part]
_Mamá:_ ¿Por qué estarías avergonzada?

[.discourse-part]
_María:_ Porque pensarías que yo estoy haciendo algo a ocultas.

[.discourse-part]
_Mamá:_
Supongo que no te gustaría que yo pensara que eres una persona que hace cosas ocultas.

[.discourse-part]
_María:_ Oh, no lo soportaría.

[.discourse-part]
_Mamá:_
¿Por qué te disgustaría tanto que yo pensara que haces cosas a ocultas?

[.discourse-part]
_María:_ Porque es algo muy vergonzoso.

[.discourse-part]
_Mamá:_ Pero, supón que estuvieras muy segura de que estoy fuera de la casa,
y que no hay peligro de ser vista por alguien;
y entonces sintieras el deseo de rebuscar dentro de mis gavetas, o leer mis papeles,
o agarrar el pastel, o cualquier cosa por el estilo;
¿lo considerarías como algo vergonzoso?

[.discourse-part]
_María:_ No creo que estaría tan avergonzada, mamá,
si estuviera segura de que no me verían.

[.discourse-part]
_Mamá:_ Entonces, ¿no es vergonzoso entrometerte en los asuntos de otras personas,
o tomar lo que no te pertenece, si no te ven cuando lo haces?
¿Eso es lo que quieres decir?

[.discourse-part]
_María:_ ¡Oh, no mamá! Hacer esas cosas es muy malo,
ya sea que alguien me vea haciéndolas o no.

[.discourse-part]
_Mamá:_ Entonces,
¿no deberías estar tan avergonzada de hacerlas cuando estás sola,
como lo estarías si alguien te estuviera viendo?

[.discourse-part]
_María:_ Sí, creo que debería estarlo.

[.discourse-part]
_Mamá:_ ¿Crees que es posible estar completamente sola?

[.discourse-part]
_María:_ Oh, sí mamá, a menudo me encuentro sola.

[.discourse-part]
_Mamá:_ No me refiero a estar sola,
en cuanto a no tener a nadie contigo que tus ojos puedan ver; sino me refiero a que,
¿hay algún momento de tu vida en el que alguien, y alguien muy Grande,
no te esté mirando?
Si crees que sí existe esa posibilidad, entonces te encuentras en un gran error.
Ve al Salmo ciento treinta y nueve, y léeme los primeros cuatro versículos.

[.discourse-part]
_María:_ "`Oh Jehová, tú me has examinado y conocido.
Tú has conocido mi sentarme y mi levantarme; has entendido desde lejos mis pensamientos.
Has escudriñado mi andar y mi reposo, y todos mis caminos te son conocidos.
Pues aún no está la palabra en mi lengua, y he aquí, oh Jehová, tú la sabes toda.`"

[.discourse-part]
_Mamá:_ Así que ves, mi niña, que nunca estás sola; y si te avergüenzas de que yo,
o cualquiera de tus prójimos, te encontremos haciendo algo a escondidas, algo vergonzoso,
o alguna cosa necia,
¡muchas más razones tienes de avergonzarte por ser hallada culpable de deshonra,
necedad y engaño, ante los ojos de un Dios puro y santo!
Es Su divino y buen Espíritu en tu corazón que te
hace consciente de lo que es corrupto e indigno.
Por lo tanto, préstale siempre atención, con reverencia y humildad;
y cuando estés tentada a hacer algo malo,
no te preguntes si deberías estar avergonzada si yo te encontrara haciéndolo;
sino pregúntate a ti misma, ¿estoy avergonzada de que Dios me vea haciendo esto?
Y como la causa de todo mal se encuentra en el corazón,
y todos los pensamientos vanos y pecaminosos surgen de ahí,
ten presente esta breve y buena oración en tu mente: "`Crea en mí, oh Dios,
un corazón limpio, y renueva un espíritu recto dentro de mí.`"^
footnote:[Salmo 51:10]
