== Diálogo IV

[quote.section-epigraph, , Proverbios 20:11]
____
_Aun el muchacho es conocido por sus hechos,
si su conducta fuere limpia y recta._
____

[.discourse-part]
_Mamá:_ María, cuando me estabas leyendo esta mañana,
¿te acuerdas que te pedí que pararas?;
y cuando me preguntaste por qué lo hice antes de que terminaras tu lección,
yo te dije que te diría la razón en otro momento.
¿Quieres escucharla?

[.discourse-part]
_María:_ Si así lo quieres, mamá. . Mamá: No, es como tú quieras.
Si crees que te va a doler escuchar la razón, no te obligaré a oírla.

[.discourse-part]
_María:_ Mamá, creo que era porque estabas un poco disgustada conmigo,
que me pediste que parara de leer.

[.discourse-part]
_Mamá:_ Entonces,
¿estás consciente de que estabas haciendo algo que
me molestaba mientras leías tu lección? Veamos,
noto que hay una pequeña consciencia de que algo está mal.
¿Estás consiente, no es así,
de que estabas fingiendo no saber el significado de aquella u otra palabra,
cuando te preguntaba; y que me di cuenta de tu simulación? ¿Acaso no es este el problema?

[.discourse-part]
_María:_ Bueno, mamá,
creo que sí sabía el significado de una o dos de las palabras que fingí no conocer;
pero quería que tuvieras una linda y larga conversación conmigo,
y no pude conseguir que hicieras lo que deseaba.

[.discourse-part]
_Mamá:_ ¡Entonces decidiste resolverlo de esta forma tan torcida!
Bueno, mi querida, en otra ocasión, cuando desees cualquier cosa,
pregunta de forma clara y abierta si te pueden conceder lo que pides,
y no dejes que el oscuro y sutil espíritu te ponga
hacer esta clase de artimañas para lograrlo.
Sin embargo, creo, María, que, si tratas de recordar,
tú y yo hemos tenido más de una vez una conversación sobre este tema.
No es en absoluto la primera vez que he tenido motivos para
advertirte de esta tendencia a fingir algo que no es cierto.
Por ejemplo, algunas veces finges ... . María: ¡Oh, querida mamá! Por favor,
no uses esa palabra tan fea de "`fingir.`"

[.discourse-part]
_Mamá:_ ¿No es el _acto_ mucho más feo que la _palabra?_

[.discourse-part]
_María:_ ¡Oh, sí! Pero, no veo lo feo que es hasta que me lo dices.

[.discourse-part]
_Mamá:_ Pero, lo verías, mi querida hija,
si le prestaras más atención a la luz verdadera dentro de ti,
que es ese sentimiento de bondad que hace que la simple idea de fingir te resulte vergonzosa.

[.discourse-part]
_María:_ ¿Cómo sabes que estoy fingiendo mamá, cuando ni yo misma lo sé?

[.discourse-part]
_Mamá:_ Lo sabes cuando te lo señalo.

[.discourse-part]
_María:_ Sí, pero, ¿qué te hace capaz de señalármelo?

[.discourse-part]
_Mamá:_ Una profunda familiaridad con mi propio corazón,
que es tan naturalmente malo como el tuyo; y una atención reverente al buen Espíritu,
que me hace capaz de distinguir entre la verdad y la falsedad.

[.discourse-part]
_María:_ ¡Oh,
mamá! ¡Qué grande y terrible es este buen
Espíritu! ¡Siento temor cuando pienso en lo cerca que está de mí!

[.discourse-part]
_Mamá:_ ¿Desearías que estuviera más lejos de ti?

[.discourse-part]
_María:_ Creo que algunas veces sí quisiera, un poquito.

[.discourse-part]
_Mamá:_
Te gustaría más que no te interrumpiera cuando finges
y cuando juegas a ser alguien que no eres.
No quieres ver el mal que está en tu corazón, ¿cierto?

[.discourse-part]
_María:_ No sé mamá, me gusta verlo, pero a la vez no me gusta.

[.discourse-part]
_Mamá:_ El hecho es, mi querida, que tienes dos naturalezas en ti, una buena y otra mala;
y "`éstas se oponen entre sí.`"^
footnote:[Gálatas 5:17]
Pero como la naturaleza mala es todavía la más fuerte de las dos,
se coloca por encima de la otra,
y de vez en cuando sale a relucir su verdadero mal aspecto,
y hace todas esas artimañas ridículas; y sería un poco mejor si solo fueran ridículas.
Sin embargo, son tan pecaminosas como ridículas,
y eso hace que yo tenga tanto interés en señalarte
la necesidad de velar en contra de ellas.

[.discourse-part]
_María:_ Gracias, mamita.
Me gusta que me señales estas cosas;
porque a veces no estoy consciente de ellas hasta que me las muestras.

[.discourse-part]
_Mamá:_ Sí, querida mía, confieso que no estás consciente.

[.discourse-part]
_María:_ Pero, mamá, me pregunto ¿por qué no estoy consciente?,
puesto que la luz buena de la que hablas está en mí, para mostrarme el mal.

[.discourse-part]
_Mamá:_ Pero, si no estás bien familiarizada con esta luz buena,
y con su manera de enseñar, y más importante aún,
si no eres muy _obediente_ cuando te muestra lo que está mal,
nunca comprenderás tu propia naturaleza,
y estarás inclinada a creer que todo está bien en ti, cuando en realidad está muy mal.
Es por el simple hecho de que los pobres pecadores ignoran tanto el poder
y el uso de la luz verdadera (que brilla en sus corazones entenebrecidos),
que a menudo llegan a tal punto de insensibilidad,
que no reconocen en lo absoluto que tienen esta luz.
Como Job, aquel santo hombre, dijo de tales personas: "`Ellos son los que,
rebeldes a la luz, nunca conocieron sus caminos, ni estuvieron en sus sendas.`"
(capítulo 24:13.)

[.discourse-part]
_María:_ Mamá, mientras me hablas de esta luz verdadera, siento tanto amor por ella,
que me parece que nunca más haré nada de lo que ella me muestre como malo.
Pero luego, después de un ratito se me olvida,
y vuelvo a caer en algo de lo que me arrepiento.
¿Cómo es que esto sucede?

[.discourse-part]
_Mamá:_ En parte debido al descuido propio de tu edad,
que te impide velar por tus pensamientos y deseos; y, por otra parte,
debido al odio que proviene del lado malo de tu naturaleza en contra de lo bueno;
un odio que te impide orar fervientemente a Dios
para que Su luz verdadera se incremente en ti,
dándote más y más de Su Santo Espíritu.

[.discourse-part]
_María:_ ¡Oh, mamá! Realmente deseo que esta luz verdadera crezca.
Quiero ser buena.
Siempre lamento y me avergüenzo cuando veo estas horribles
malas hierbas en mi corazón. ¿Qué es lo que las hace surgir,
si me desagradan tanto?

[.discourse-part]
_Mamá:_ El amor al yo, mi querida--el deseo de hacer notar al yo.
Por ejemplo, hoy estaba bastante seria, sin ganas de conversar,
y tú hiciste varios intentos tratando de llamar mi atención, pero no pudiste lograrlo.
Así que, para conseguirlo,
te pusiste a fingir que no sabías el significado de aquella u otra palabra,
y que a veces no podías encontrar el lugar donde quedaste en tu lectura,
y cosas de ese tipo, con el único fin de hacer relucir el yo;
hasta que viendo lo que pretendías y quién estaba gobernándote,
decidí pedirte que pararas, y te dije que te explicaría la razón en otra ocasión.

[.discourse-part]
_María:_ Bueno, mamá, me di cuenta de cuál era la razón,
incluso antes de que me lo dijeras.
¿Pero a qué te refieres cuando dices "`quién era`" el que me gobernaba?

[.discourse-part]
_Mamá:_ Me refiero al espíritu maligno, que es el enemigo de todo lo bueno,
y del que lees en las Escrituras como el malvado que, como león rugiente,
anda alrededor buscando a quién devorar.
El que se llama satanás, o el diablo, estaba guiándote a la necedad y al pecado.

[.discourse-part]
_María:_ ¿También está tan cerca de mí, mamá?

[.discourse-part]
_Mamá:_ Está muy cerca,
y siempre buscando exaltarte con pensamientos vanos acerca de ti misma,
y haciéndote sentir ansiosa de ser notada, e infeliz cuando no logras hacerlo.

[.discourse-part]
_María:_ Pero mamá, ¿por qué es tan peligroso amarnos a nosotros mismos,
ya que no hay nadie tan cerca de nosotros para amar?

[.discourse-part]
_Mamá:_ Es peligroso, por muchas razones más de las que puedo contarte ahora,
pues ya hemos hablado bastante por el momento.
Pero una de las razones (si no hubiera otras) por las que
es peligroso amarnos demasiado a nosotros mismos,
es porque es contrario a la voluntad de Dios, y al ejemplo de nuestro bendito Salvador,
que dice, "`si alguno quiere venir en pos de mí, niéguese a sí mismo,
tome su cruz cada día, y sígame.`"
Ahora bien, nunca nos negaremos a nosotros mismos si estamos llenos de amor propio.

[.discourse-part]
_María:_ Mamá, no creo entender exactamente lo que significa negarnos a nosotros mismos.

[.discourse-part]
_Mamá:_ Bueno, quizás mañana podremos hablar un poquito más sobre ese tema.
