== Diálogo V

[quote.section-epigraph, , Mateo 16:22-23]
____
_Y Pedro, tomándole aparte, comenzó a reprenderle, diciendo: Señor,
ten compasión de ti; en ninguna manera esto te acontezca.
Entonces Él, volviéndose, dijo a Pedro:
Quítate de delante de mí Satanás._
____

[.discourse-part]
_Mamá:_ María, ayer querías saber lo que significaba negarnos a nosotros mismos.
Creo que puedo darte una idea de ello con algo que ocurrió hoy.

[.discourse-part]
_María:_ Si así lo deseas, mamá;
aunque no se me ocurre nada en particular que haya pasado hoy.

[.discourse-part]
_Mamá:_ ¿No recuerdas que el cartero me trajo una carta,
justo cuando estaba a punto de escucharte leer y decir tus lecciones esta mañana?

[.discourse-part]
_María:_ ¡Oh, sí! Y yo deseaba que la abrieras.

[.discourse-part]
_Mamá:_ Sí, tú querías que yo la abriera.
Pero, ¿por qué? ¿Qué importancia tendría para ti que yo la abriera o no?
No estaba dirigida a ti.

[.discourse-part]
_María:_ Oh, no, mamá, eso lo sé.

[.discourse-part]
_Mamá:_ Pero, sin embargo, sentiste mucha curiosidad por saber su contenido,
y de quién provino.
¿No fue este el caso?

[.discourse-part]
_María:_ Sí, mamá.

[.discourse-part]
_Mamá:_ Bueno, si sentiste un gran deseo de saber su contenido,
aunque no tenías nada que ver con ello, ¿no crees que yo deseaba saberlo aún más?

[.discourse-part]
_María:_ Oh, sí mamá. Me preguntaba cuál podría ser el motivo de dejarla sobre la mesa,
durante todo el tiempo que estaba leyendo y diciendo mis lecciones.

[.discourse-part]
_Mamá:_ Me estaba negando a mí misma.
Me hubiera gustado mucho más leerla; pero tenía que atender algo más en ese momento,
y entonces me dije a mí misma: "`No, debes esperar.`"

[.discourse-part]
_María:_ Pero, mamá, ¿no podrías haber dejado ese "`algo más`" para otro momento?

[.discourse-part]
_Mamá:_ Desde luego, podría haberlo hecho;
pero entonces me habría equivocado en varios puntos.
En primer lugar, habría desobedecido a la luz,
que me mostraba que mi deber en ese entonces era escucharte leer y decir tus lecciones.
También me mostró, que, si leía la carta,
estaría satisfaciendo una curiosidad muy vana y equivocada en ti
que te hizo estar tan ansiosa de que se abriera la carta,
que apenas podías prestarle atención a tus lecciones;
pues seguías con tus ojos puestos en la carta y luego en mí,
con la esperanza de obtener algo de información al respecto.
La luz me mostró que esta curiosidad nace de tu propia voluntad,
y también me mostró que debo negarla y decepcionarla.

[.discourse-part]
_María:_ ¡Oh,
mamá! ¿Pudiste darte
cuenta de que deseaba que abrieras la carta?
Bueno, pensé que jamás lo notarías. Pensé que lo había ocultado muy bien.

[.discourse-part]
_Mamá:_ No, mi querida.
Afortunadamente, no es muy difícil saber lo que pequeños niños como tú desean.
Pero para continuar con lo que estaba diciendo;
esta conducta que viste en mí esta mañana,
te permite entender algo de lo que quería decir con negarnos a nosotros mismos.

[.discourse-part]
_María:_ Sí, mamá, puedo entender lo que significa negarnos a nosotros mismos;
pero aún no puedo ver por qué debemos hacerlo.

[.discourse-part]
_Mamá:_ Supongamos que te llevara conmigo a una tienda de repostería,
y me pidieras que te comprara unas galletas, unos pasteles,
unas tartas y cualquier otra cosa que desearas comer; ¿crees que debería complacerte?

[.discourse-part]
_María:_ No, mamá, sé que no lo harías.

[.discourse-part]
_Mamá:_ ¿Por qué debería negarte estas cosas?

[.discourse-part]
_María:_ Porque serían malas para mí.

[.discourse-part]
_Mamá:_ Pero, supongo que te gustaría mucho tener algunas de esas cosas,
si pudieras tenerlas.

[.discourse-part]
_María:_ Sí, creo que me gustaría.

[.discourse-part]
_Mamá:_ ¿Y aún así te contentas con renunciar a ellas,
y pensar que yo sé bien lo que es mejor para ti?

[.discourse-part]
_María:_ Oh, sí mamá.

[.discourse-part]
_Mamá:_ Bien, entonces mi querida hija,
si puedes confiar en tus padres terrenales para guiarte por el mejor camino,
¿cuánto más deberías obedecer los mandatos de tu Padre celestial?;
y cuando Él te pida negarte a ti misma,
¿cuánto más debes someterte a Él sin preguntarle "`por qué?`" Pero,
aunque sea difícil para ti, a tu edad,
entender todo el propósito del mandato de negarte a ti misma y tomar tu cruz,
sin embargo,
seguramente habrás aprendido lo suficiente de estas conversaciones que hemos tenido,
para ver qué criatura tan vana, tonta y egoísta serías,
si nunca estuvieras obligada a controlar tu propia voluntad,
sino que pudieras hacer todo lo que quisieras en todas las cosas.

[.discourse-part]
_María:_ Pero, mamá, ¿por qué mi voluntad es tan mala,
que necesita siempre ser controlada?

[.discourse-part]
_Mamá:_ Esta es una pregunta que nos llevaría a una conversación más larga,
de lo que sería conveniente, a esta hora tan tarde.
Mañana, si es posible, retomaremos este tema.
Solamente,
permíteme señalarte un impactante versículo en las Escrituras que
muestra claramente cuán repulsivo fue para el bendito Jesús,
cualquier intento de persuadirlo para que no sufriera dolor y no se negara a Sí mismo;
pues siempre debemos sufrir algo de dolor cuando nos negamos a nosotros mismos.
Acuérdate que Pedro fue uno de Sus discípulos privilegiados; él, junto con Jacobo y Juan,
lo acompañaban usualmente cuando otros no tenían ese privilegio.
Aún así, cuando Pedro quiso que Jesús evitara los sufrimientos que le esperaban,
le dijo (sin duda,
haciéndolo de esa forma tan persuasiva que le encanta a nuestra naturaleza malvada),
"`Señor, ten compasión de ti;
en ninguna manera esto te acontezca;`" el manso y humilde Jesús,
con una santa indignación, lo rechazó con esta severa reprensión:
"`¡quítate de delante de mí, Satanás!`" No a Pedro, Su amigo y discípulo;
sino al Pedro que estaba entonces tan fuertemente
bajo la influencia de un sentimiento falso,
¡que mereció y recibió el nombre de satanás!
