== Diálogo VI

[quote.section-epigraph, , Isaías 1:3]
____
_El buey conoce a su dueño, y el asno el pesebre de su señor: Pero Israel no conoce,
mi pueblo no tiene entendimiento._
____

[.discourse-part]
_Mamá:_ María, ahora estoy lista para responder, según mi medida,
la pregunta que me hiciste la otra noche, que si bien recuerdo,
era ¿por qué es necesario controlar tu voluntad?

[.discourse-part]
_María:_ Sí,
mamá. Me gustaría saber por qué mi voluntad es tan mala
como para que necesite ser controlada siempre.

[.discourse-part]
_Mamá:_ Esta pregunta, querida mía, nos lleva a temas muy solemnes; y, por lo tanto,
debes prestar mucha atención,
meditar en ellos y considerar qué es lo que vas a decir
antes de que preguntes cualquier cosa al respecto.
Todo lo que puedo decirte,
o lo que vayas a aprender sobre la causa de que tu voluntad sea mala,
se encuentra en la Biblia.
¿Recuerdas haber leído, "`y creó Dios al hombre a su imagen?`"

[.discourse-part]
_María:_ Sí, mamá;
y le ordenó que no comiera del fruto del árbol del conocimiento del bien y del mal;
porque el día que comiera de él, ciertamente moriría. . Mamá: Sí,
y en ese mismo momento sufrió una muerte muy espantosa.

[.discourse-part]
_María:_ Querida mamá, yo pensaba que había vivido varios cientos de años,
y que había tenido dos hijos, y... . Mamá:
Mantente quieta y déjame explicarte qué tipo de muerte experimentó Adán
cuando desobedeció al Señor. No experimentó la muerte del cuerpo,
sino una mucho peor.
Su alma,
que fue creada a la imagen de Dios--esa preciosa imagen--__eso__ fue
precisamente la parte de él que murió. Y es por eso,
que ahora todos los hijos de Adán no tienen la imagen de Dios, sino que, en lugar de eso,
la única imagen que continuamente está en sus pensamientos es su propia imagen.

[.discourse-part]
_María:_ Por favor, mamá,
me puedes decir lo que significa una imagen;
porque creo que no te puedo entender completamente.

[.discourse-part]
_Mamá:_ Ve y mírate en el espejo, y dime lo que ves.

[.discourse-part]
_María:_ Me veo a mí misma.

[.discourse-part]
_Mamá:_ ¿Cómo es posible?
No es posible que te veas a ti misma; pues,
estás delante del espejo y lo que estas mirando es una figura de ti misma,
que mira en dirección opuesta.

[.discourse-part]
_María:_ Supongo entonces, mamá, que lo que veo es una imagen de mí misma.

[.discourse-part]
_Mamá:_ Exactamente.
Te representa a ti misma.
Es tu imagen; y puedes entender muy bien la naturaleza de esta imagen,
y te satisfaces mucho (¡demasiado por desgracia!) al contemplarla.
Casi nunca te cansas de mirar cómo lucen tus rizos, y cómo tu... . María: Oh mamá,
sé que esas son cosas muy tontas; por favor,
háblame de alguna otra cosa más. Ya entendí lo que es una imagen.

[.discourse-part]
_Mamá:_ Sabes lo que es una imagen humana, querida hija, que es la imagen que llevas;
pero no tengo palabras suficientes que puedan expresarte cuál fue
esa imagen que Adán llevó antes de desobedecer a Dios y perderla.
Basta con decir que era la imagen de Dios--¡toda gloriosa, hermosa,
majestuosa y divina! --de modo que se le permitió, o, mejor dicho,
fue _creado con el propósito_ de deleitarse en ella;
porque cuando se deleitaba en esta imagen, se deleitaba en Dios, a quien se asemejaba.
Si no fuéramos criaturas caídas y pecaminosas,
no tendríamos ningún placer en nada que no fuera Dios.
Su voluntad sería la nuestra; no sabríamos lo que es pensar en nosotros mismos,
o preocuparnos por lo nuestro.
En cambio, ahora, no pensamos ni nos preocupamos por nada más que eso,
nuestra voluntad es todo para el yo.
Continuamente dice,
¿qué puedo obtener __yo?__--¡dame algo __a mí!__--__¡yo__ necesito estar bien atendido!

[.discourse-part]
_María:_ Oh, mamá, ¡no creo que yo esté diciendo eso todo el tiempo!

[.discourse-part]
_Mamá:_ No lo haces con tus labios, mi querida.
Pero considera por un momento,
y creo que encontrarás que el yo es lo más importante
que hay en tu mente durante la mayor parte del día;
y sería muy peligroso para ti y para todos los demás,
si no se mantiene sometido bajo el cuidado y la instrucción de otros; y espero que,
en cierta medida, con tus propios esfuerzos tú también lo resistas.
Aún con todas las enseñanzas que recibes, todas las restricciones que se te imponen,
tu voluntad considera muy difícil pensar en Dios,
y aún más difícil deleitarse en Él. ¿No es este el caso?

[.discourse-part]
_María:_ Oh, mamá, sería muy mala si dijera que no;
porque me temo que lo que dices es cierto.

[.discourse-part]
_Mamá:_ No tengas miedo de hablar la verdad, querida hija.
Es necesario que entiendas exactamente la gran corrupción de tu corazón,
de lo contrario no buscarás el remedio fervientemente.

[.discourse-part]
_María:_ ¡Entonces hay un remedio, mamá! ¡Oh, cuánto me alegro!
Explícamelo, por favor.

[.discourse-part]
_Mamá:_ En el momento en que Adán perdió su hermosa y divina vida,
a su buen Creador le plació prometerle que la Semilla
de la mujer heriría la cabeza de la serpiente;
que fue como si Dios le hubiera dicho,
"`Te enviaré a un Amigo que te librará de esta naturaleza de serpiente malvada,
que has traído sobre ti al desobedecer Mis mandamientos.`"
Este gran redentor no vendría al mundo hasta varios cientos de años después;
pero una medida de Su santo Espíritu le fue dada a Adán,^
footnote:[Ver Génesis 3:15; Deuteronomio 30:14; Job 32:8; Ecclesiastes 3:11; Miqueas 6:8;
Juan 1:9; Romanos 1:19]
como su ayuda y liberación de esa naturaleza malvada
que había obtenido al satisfacer su propia voluntad,
y comido del fruto prohibido.

[.discourse-part]
_María:_ Oh, mamá,
¡qué castigo más terrible por algo tan pequeño como haber comido de un fruto!

[.discourse-part]
_Mamá:_ No fue el acto en sí lo que hizo el pecado grave;
fue el egoísmo ingrato y rebelde que esto representaba,
lo que hizo que fuera tan severamente castigado.
Supón que yo fuera diez mil veces más amable y amorosa contigo de lo que soy ahora,
con todo, mi amor no sería nada comparado con el amor que Dios tuvo por Adán. Pero,
supón que yo te diera permiso para que disfrutaras y jugaras en el jardín,
y que te hubiera provisto de todo lo posible que pudiera pensar para tu satisfacción,
y que te dijera: "`María, puedes comer de cualquier fruto que quieras;
pero no comas de tal árbol, porque lo que tomes de él,
te envenenará.`" Y supongamos que despreciaras lo que hubiera provisto
para tu felicidad y tomaras del árbol envenenado--¿no estarías
mostrando una actitud muy egoísta que nace de tu propia voluntad?

[.discourse-part]
_María:_ Sí, mamá, merecería ser castigada.

[.discourse-part]
_Mamá:_ Pero supón que me fuera posible,
no sólo proveerte de un precioso lugar para que jugaras en él,
y agradables frutos para que comieras de ellos,
sino también llenar tu mente con pensamientos tan
placenteros que te hicieran siempre buena y feliz,
y luego,
una persona malvada y envidiosa viniera y te persuadiera de que debías ser aún más feliz,
aún más buena, y hasta más sabia, si comieras del fruto prohibido.
¿No mostrarías una actitud muy codiciosa, avara, además de egoísta y terca,
si le hicieras caso?

[.discourse-part]
_María:_ Sí, verdaderamente lo haría. Debería estar satisfecha con ser buena y feliz,
y no desear más de lo que se me hubiera dado.

[.discourse-part]
_Mamá:_ Entonces, si encontraras, tan pronto como hubieras comido del fruto envenenado,
que tus pensamientos hermosos, felices y buenos se hubieran ido,
y que en su lugar habrías obtenido un montón de pensamientos oscuros,
codiciosos y avariciosos,
¿no crees que tendrías justo lo que te merecías y que lo habrías ocasionado tú misma?

[.discourse-part]
_María:_ Sí, mamá, no tendría que culpar a nadie más excepto a mí misma;
porque no debí haber escuchado a la persona malvada que me persuadió a desobedecerte.

[.discourse-part]
_Mamá:_ Entonces, ahora puedes comprender por qué el castigo de Adán fue tan severo;
y ciertamente,
no podría haber tenido una consecuencia mayor que la de perder
una naturaleza tan bendita y feliz por una malvada en su lugar.
Pero, aún en esta infeliz condición, a la bondad de Dios le plació acudir en su ayuda,
devolviéndole una pequeña semilla o medida de esa bendita naturaleza que había perdido.
Fue puesta en su corazón y está puesta en el corazón de todos,
para que nos enseñe lo que es bueno.

[.discourse-part]
_María:_ Entonces,
¿supongo que esta es la luz verdadera y el buen Espíritu
del que hemos estado hablando por tanto tiempo,
mamá?

[.discourse-part]
_Mamá:_ Sí, mi querida hija,
este es el que liberta del mal, y el que guía a todo bien,
que nos muestra cuando nuestra voluntad es mala, y que nos llama a negarla.
Si Adán le hubiera prestado atención a este maestro
en lugar de prestarle atención a la serpiente malvada,
quien era el diablo,
habría escapado de toda la miseria que trajo sobre sí mismo y sobre nosotros también;
porque como consecuencia de su desobediencia, todos somos pecadores,
habiendo nacido según su imagen, y no según la imagen de Dios.

[.discourse-part]
_María:_ Pero, mamá,
dijiste que este buen libertador vino al mundo varios
cientos de años después de que Adán pecara.

[.discourse-part]
_Mamá:_ Sí, este gran libertador fue el Señor Jesucristo,
quien en las Escrituras es llamado el segundo Adán,
porque Él repara todo el daño que el primer Adán ha causado.

[.discourse-part]
_María:_ ¡Cómo es que Él hace eso, mamá?

[.discourse-part]
_Mamá:_ Haciendo que la naturaleza mala vuelva a ser buena nuevamente.
Él se convirtió en un hombre como Adán, e hizo lo que Adán debió haber hecho,
obedeciendo perfectamente la voluntad de Dios en todas las cosas.
Pero en estos momentos este tema está más allá de tu comprensión; por lo tanto,
por ahora hablaremos solamente de lo que pienso que puedes comprender.
Permíteme hacerte algunas preguntas con respecto a lo que hemos estado conversando.
¿A imagen de quién fue creado Adán primero?

[.discourse-part]
_María:_ A imagen de Dios, que era una imagen hermosa y gloriosa.

[.discourse-part]
_Mamá:_ ¿Cómo perdió esta imagen?

[.discourse-part]
_María:_ Obedeciendo a su propia voluntad, y desobedeciendo a Dios,
al comer del fruto prohibido.

[.discourse-part]
_Mamá:_ Él obtuvo después una vida, una naturaleza y una imagen propias,
en lugar de la vida, la naturaleza y la imagen de Dios.
¿Y la naturaleza que obtuvo fue buena?

[.discourse-part]
_María:_ No, fue una muy mala.

[.discourse-part]
_Mamá:_ ¿Tenemos nosotros la misma naturaleza mala?

[.discourse-part]
_María:_ Sí, nacemos a imagen y semejanza de Adán.

[.discourse-part]
_Mamá:_ ¿Podemos esperar recuperar la imagen de Dios que murió en Adán?

[.discourse-part]
_María:_ Sí; hay una pequeña semilla de ella que nos ha sido devuelta,
para mostrarnos lo que es bueno y hacer que lo amemos.

[.discourse-part]
_Mamá:_ ¿Cómo se llama?

[.discourse-part]
_María:_ Se llama la "`luz.`"
Es la "`luz verdadera que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9 Reina Valera de Gómez]

[.discourse-part]
_Mamá:_ ¿Tienes algo de esta luz?

[.discourse-part]
_María:_ Sí, mamá. . Mamá: Entonces, recuerda, querida hija, obedecerla;
y sobre todas las cosas,
recuerda que te llama a negar todo el mal que heredaste de Adán.
